services:
  backend:
    image: mlactionsdeploy.azurecr.io/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  frontend:
    image: mlactionsdeploy.azurecr.io/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
